baseURL: 'https://blog.summittservices.com'
title: Summitt Dweller's Blog
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
ignoreErrors:
  - error-remote-getjson
footnoteReturnLinkContents: ^
copyright: Mark McFate
enableRobotsTXT: true
pygmentsCodeFences: true
canonifyurls: true
paginate: 6
theme: bootstrap-bp-hugo-theme

sitemap:
  changefreq: weekly
  priority: 0.5

permalinks:
  posts: '/:year/:month/:slug/'
  post: '/:year/:month/:slug/'
  pages: '/:slug/'
  page: '/:slug/'

params:
  author:
    name: Mark McFate
  description: "An old fart's memory dump: Lots of code, some life experiences, and a little humor. No politics!"
  customDateFormat: 2006-01-02
  themeColor: blue
  startPageColumns: true 
  showListsGrouped: true
  showPostSummary: true 
  alwaysExpandMenu: true
  staticCloudPrefix: https://summittservices.blob.core.windows.net/summitt-dweller-blog

social:
  github: SummittDweller
  gitlab: ''
  stackoverflow: ''
  bitbucket: ''
  jsfiddle: ''
  codepen: ''
  deviantart: ''
  flickr: ''
  behance: ''
  dribbble: ''
  wordpress: ''
  medium: ''
  linkedin: ''
  linkedin_company: ''
  foursquare: ''
  xing: ''
  slideshare: ''
  facebook: ''
  googleplus: ''
  reddit: ''
  quora: ''
  youtube: ''
  vimeo: ''
  whatsapp: ''
  instagram: ''
  tumblr: ''
  twitter: ''
  skype: ''
  snapchat: ''
  pinterest: ''
  telegram: ''
  discord: ''
  email: ''

# module:
#   imports:
#     - path: github.com/hugomods/icons/vendors/bootstrap
#     - path: github.com/hugomods/icons/vendors/font-awesome

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
      pre: <i class='fas fa-heart'></i>
    - identifier: microposts
      name: Microposts
      url: /micropost/
      weight: 20
      pre: <i class='bi bi-journal'></i>
  footer:
    - identifier: about
      name: About
      url: /about/
      weight: 10
      pre: <i class='fa fa-address-card'></i>
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
      pre: <i class='fas fa-folder'></i>
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
      pre: <i class='fas fa-tags'></i>

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
